"""Public schema exports for the UFC feature package."""

from __future__ import annotations

from .internal import (
    AuthResult,
    FighterList,
    FighterMutationResult,
    FighterQueueResult,
    FighterSummary,
    RegistrationResult,
    SubscriptionStatusResponse,
    SubscriptionSummaryItem,
    SubscriptionSummaryList,
    UserExistsResult,
    UserProfile,
)
from .requests import (
    AuthLoginRequest,
    AuthRegistrationRequest,
    CreateFighterRequest,
    FighterListParams,
    FighterListQueryParams,
    FighterQueueRequest,
    FighterSearchParams,
    FighterSubscriptionParams,
    SubscriptionToggleRequest,
    UpdateFighterRequest,
)
from .responses import (
    AuthEnvelope,
    FighterListData,
    FighterListEnvelope,
    FighterMutationEnvelope,
    FighterQueueEnvelope,
    RegistrationEnvelope,
    SubscriptionSummaryEnvelope,
    SubscriptionStatusEnvelope,
    UfcErrorData,
    UfcErrorDetail,
    UfcErrorResponse,
    UserExistsEnvelope,
    UserProfileEnvelope,
    UfcResponseBase,
)

__all__ = [
    "AuthResult",
    "FighterList",
    "FighterMutationResult",
    "FighterQueueResult",
    "FighterSummary",
    "RegistrationResult",
    "SubscriptionStatusResponse",
    "SubscriptionSummaryItem",
    "SubscriptionSummaryList",
    "UserProfile",
    "UserExistsResult",
    "AuthLoginRequest",
    "AuthRegistrationRequest",
    "CreateFighterRequest",
    "FighterListParams",
    "FighterListQueryParams",
    "FighterSearchParams",
    "FighterQueueRequest",
    "FighterSubscriptionParams",
    "UpdateFighterRequest",
    "SubscriptionToggleRequest",
    "FighterListEnvelope",
    "FighterMutationEnvelope",
    "FighterQueueEnvelope",
    "SubscriptionSummaryEnvelope",
    "SubscriptionStatusEnvelope",
    "FighterListData",
    "AuthEnvelope",
    "RegistrationEnvelope",
    "UserExistsEnvelope",
    "UserProfileEnvelope",
    "UfcErrorData",
    "UfcErrorDetail",
    "UfcErrorResponse",
    "UfcResponseBase",
]
