"""Semantic search feature defaults."""

from __future__ import annotations

import os

ENABLED = os.getenv("SEMANTIC_SEARCH_ENABLED", "true").lower() == "true"
INDEXING_ENABLED = os.getenv("SEMANTIC_INDEXING_ENABLED", "true").lower() == "true"

DEFAULT_LIMIT = int(os.getenv("SEMANTIC_SEARCH_DEFAULT_LIMIT", "10"))
DEFAULT_SCORE_THRESHOLD = float(os.getenv("SEMANTIC_SEARCH_DEFAULT_SCORE_THRESHOLD", "0.0"))
CONTEXT_MAX_TOKENS = int(os.getenv("SEMANTIC_SEARCH_CONTEXT_MAX_TOKENS", "4000"))

SEARCH_TIMEOUT = float(os.getenv("SEMANTIC_SEARCH_TIMEOUT", "10.0"))
TOTAL_TIMEOUT = float(os.getenv("SEMANTIC_TOTAL_TIMEOUT", "15.0"))

RATE_LIMIT_PER_MINUTE = int(os.getenv("SEMANTIC_RATE_LIMIT_REQUESTS", "60"))
RATE_LIMIT_WINDOW_SECONDS = float(os.getenv("SEMANTIC_RATE_LIMIT_WINDOW", "60.0"))

SEARCH_MODE_SEMANTIC = "semantic"
SEARCH_MODE_HYBRID = "hybrid"
SEARCH_MODE_KEYWORD = "keyword"
SEARCH_MODE_SESSION_SEMANTIC = "session_semantic"
SEARCH_MODE_SESSION_HYBRID = "session_hybrid"
SEARCH_MODE_MULTI_TIER = "multi_tier"
DEFAULT_SEARCH_MODE = SEARCH_MODE_HYBRID

MULTI_TIER_TOP_SESSIONS = int(os.getenv("SEMANTIC_MULTI_TIER_TOP_SESSIONS", "3"))
MULTI_TIER_MESSAGES_PER_SESSION = int(os.getenv("SEMANTIC_MULTI_TIER_MESSAGES_PER_SESSION", "5"))

__all__ = [
    "ENABLED",
    "INDEXING_ENABLED",
    "DEFAULT_LIMIT",
    "DEFAULT_SCORE_THRESHOLD",
    "CONTEXT_MAX_TOKENS",
    "SEARCH_TIMEOUT",
    "TOTAL_TIMEOUT",
    "RATE_LIMIT_PER_MINUTE",
    "RATE_LIMIT_WINDOW_SECONDS",
    "SEARCH_MODE_SEMANTIC",
    "SEARCH_MODE_HYBRID",
    "SEARCH_MODE_KEYWORD",
    "SEARCH_MODE_SESSION_SEMANTIC",
    "SEARCH_MODE_SESSION_HYBRID",
    "SEARCH_MODE_MULTI_TIER",
    "DEFAULT_SEARCH_MODE",
    "MULTI_TIER_TOP_SESSIONS",
    "MULTI_TIER_MESSAGES_PER_SESSION",
]
